### PR TITLE
Convert `ErrorHandler.closed` to async

### PR DESCRIPTION
**Pull request by adam-fowler**
Have `ErrorHandler.closed` return a `Promise<CloseHandlerResult>` so language clients have more fliexibility in the decision of whether to restart the server. For instance displaying a dialog asking the user what they want to do.

Note: This is a breaking change. I don't know what the policy is with these

### CODE REVIEW

**Comment by dbaeumer** [comment]
Will be out on vacation soon. Has to wait until I am back.

**Comment by adam-fowler** [comment]
@dbaeumer do you have time to look at this now?

**Comment by dbaeumer** [comment]
Will look into this this week.

**Comment by adam-fowler** [comment]
Do you have any update on this? thank you

**Comment by adam-fowler** [comment]
Do you have any update on this? thank you

**Comment by dbaeumer** [comment]
Yes, working on it. Is the next thing in my pipeline.

**Comment by dbaeumer** [comment]
The PR is breaking the ErrorHandler which is something we should avoid. I created another implementation here that avoids that: https://github.com/microsoft/vscode-languageserver-node/tree/dbaeumer/obliged-thrush-olive

Will close the PR in favour of the branch above.

@adam-fowler let me know if the new implementation will work for you.

**Pull request closed without merging**
