### PR TITLE
Remove source map references when publishing

### PR DESCRIPTION
**Pull request by zachkirsch**
@dbaeumer  Take 2 of https://github.com/microsoft/vscode-languageserver-node/pull/899, which was reverted to do `compile:publish` failing. This adds more `tsconfig.publish.json`'s to the `browser`, `node`, and `common` folders of each package and the associated `references`.

# Fixes https://github.com/microsoft/vscode-languageserver-node/issues/879

## The problem 
The packages in this repo are configured to produce source maps at compile-time, which includes:
1. a reference to a source map at the bottom of each generated JS file, e.g. 
    ```js
    // lib/browser/main.js
    ...

        return browser_1.createMessageConnection(reader, writer, logger, options);
    }
    exports.createProtocolConnection = createProtocolConnection;
    //# sourceMappingURL=main.js.map
    ```
1. a source map, e.g. `lib/browser/main.js.map`

However, when the packages are published, the source maps are not uploaded because they are explicitly ignored by npm: https://github.com/microsoft/vscode-languageserver-node/blob/f72faa0975cb2aaa85ce84da819944f84e1aac52/protocol/.npmignore#L4

Therefore, the published package:
1. does include the references at the bottom of each generated JS file
1. does **not** include the actual source maps

These dangling references are causing build errors:
```
Failed to parse source map from '/home/char0n/Documents/GitHub/test/node_modules/vscode-languageserver-protocol/lib/common/utils/is.js.map' file: Error: ENOENT: no such file or directory, open '/home/char0n/Documents/GitHub/test/node_modules/vscode-languageserver-protocol/lib/common/utils/is.js.map'
``` 

## The solution

Don't produce source maps. This effectively maintains the current functionality, but removes the dangling references in the generated JS files.

### CODE REVIEW

**Comment by zachkirsch** [comment]
@dbaeumer how's this look?

**Comment by dbaeumer** [comment]
Sorry, we have endgame right now to prepare a new VS Code version. So this has to wait until beginning of April.

**Comment by zachkirsch** [comment]
Hey @dbaeumer! Just checking in here

**Comment by dbaeumer** [comment]
@zachkirsch thanks for the ping. Will do my best to get this in this milestone. I am end game champ these two month which cost a lot of my dev time.

**Comment by zachkirsch** [comment]
No stress! Game champ sounds fun but I bet it's tiring

**Comment by zachkirsch** [comment]
@dbaeumer ping on this :)

**Comment by dbaeumer** [comment]
Thanks for the ping. Will try to look into this in June.

**Comment by dbaeumer** [comment]
@zachkirsch I looked at the PR and although it adds the rights files (and we discussed it that way) I decided to try a different route. I started to write code that generates these files from a higher level description. Would be a lot easier to maintain. And I have a comparable repository where I could reuse the code. If you are interested to contribute or give feedback a start is on https://github.com/microsoft/vscode-languageserver-node/tree/dbaeumer/tsconfigGeneration

**Comment by dbaeumer** [comment]
And https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/tsconfigGeneration/tools/src/project.ts

**Comment by dbaeumer** [comment]
This got addressed by the new tsconfig file generation. The repository has now tsconfig.publish.json files.

**Pull request closed without merging**
