### PR TITLE
Add calls to validatePosition for some requests

### PR DESCRIPTION
**Pull request by davidanthoff**
This is an attempt to improve the situation described in https://github.com/microsoft/language-server-protocol/issues/946.

Be warned: I really don't know what I'm doing here. These diffs look plausible to me, but I have really no idea. I also don't know how to try the code in this repo, so as far as I can tell this compiles, but beyond that I haven't tested it :)

### CODE REVIEW

**Comment by dbaeumer** [comment]
We should never change the position of a request since the sender of the request might not be aware of this. All we can do is to reject the request if the position is outside the document range. And now that I think about this it should may be not be something that goes into the LSP libs right away since I never heard about such a problem. @davidanthoff have you tried to handle this in a custom middleware on your end to see what is actually the cause of this?

**Comment by davidanthoff** [comment]
No, I haven't tried that. Is there some pointer how I might be able to add custom middleware?

**Comment by rcjsuen** [comment]
> Is there some pointer how I might be able to add custom middleware?

@davidanthoff Maybe #322 and #628 can help?

**Comment by davidanthoff** [comment]
Yes, those pointers were super helpful!

I've added diagnostic code now in our extension (see https://github.com/julia-vscode/julia-vscode/pull/1333), lets see what we get from that. I'll report back if we find anything interesting.

Thanks for the help! I'll close this PR here, the middleware route is clearly better.

**Pull request closed without merging**
