### PR TITLE
Cleanup "installServerIntoExtension" script

### PR DESCRIPTION
**Pull request by Turbo87**
This PR removes an unused function from the script and adds a missing `var` keyword.

### CODE REVIEW

**Comment by Turbo87** [comment]
@msftclas CLA should be signed now

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by Turbo87** [comment]
🎉

**Comment by dbaeumer** [comment]
@Turbo87  Thanks!

**Pull request merged**
