### PR TITLE
Add preselect field to CompletionItem per VS Code 1.25

### LINKED ISSUE #371: Add 'preselect'  field to the CompletionItem
VS Code 1.25 adds new `preselect` field to the `CompletionItem`. The field allows completion providers to specify which item should be initially selected in the completion list. 

By default clients usually select first or last used items, which is limiting. A completion provider may choose to select different item based on other conditions, such as current code editor context, probability of use of certain items, and so on. 

This request is to add equivalent field to the CompletionItem structure therefore allowing use of preselection in VS Code from language servers as it is possible from the regular completion provider.

https://github.com/Microsoft/vscode/blob/9ba606df0ee5c2a386eac532771ac343a62f1985/src/vs/workbench/api/node/extHostTypes.ts

Per 
https://github.com/Microsoft/vscode/issues/35551
https://github.com/Microsoft/vscode/commit/62e0f34a3569f2cab4d16b2ef36dde285d39a9cf

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #371 

Do I need to rev the version up? Not sure.

### CODE REVIEW

**Comment by dbaeumer** [comment]
@MikhailArkhipov thanks for the PR. But changing the code is only half the work. This needs to be updated in the spec as well which is maintained here: https://github.com/Microsoft/language-server-protocol

I would suggest you open an item at https://github.com/Microsoft/language-server-protocol to get feedback on how we would best add the property. The problem is that this needs a capability as well since completion items travel from the client to the server as well (in code action calls) and servers might be surprised if the property got lost since clients other than VS Code will not support it.

**Comment by MikhailArkhipov** [comment]
The property is already there and works in TypeScript. The problem is that it does not work from the language server. This issue is pretty urgent. Thanks!

**Comment by MikhailArkhipov** [comment]
LSP PR https://github.com/Microsoft/language-server-protocol/pull/515

**Comment by dbaeumer** [comment]
Thanks.

**Comment by dbaeumer** [comment]
Closing. New version are available.

**Pull request closed without merging**
