### PR TITLE
Use client ID as fallback for diagnostics collection

### PR DESCRIPTION
**Pull request by remcohaszing**
This sets the language client ID as a fallback for the diagnostics collection name. If no collection name is provided, VSCode generates one. This name is visible in the diagnostics table view of the problems panel.

Problems panel table view showing several diagnostics

This can be solved for every language server integration separately, but IMO it’s nicer if this package provides a better default. An alternative is to use the name instead of the ID. I went with ID, because `typescript` in the screenshot is lower case.

### CODE REVIEW

**Comment by dbaeumer** [comment]
Makes sense. When we started we didn't have a table problems view :-)

**Comment by remcohaszing** [comment]
@dbaeumer Friendly ping. I read your comment as you finding this a good idea. I think it makes sense to include this in v10, which is in alpha now.

**Comment by dbaeumer** [comment]
@remcohaszing still agree that this is a good a change. Could you make the code adjustment I asked for.

**Comment by remcohaszing** [comment]
I don’t see any review comments. Did you maybe forget to press Submit? :sweat_smile:

**Review by dbaeumer — CHANGES_REQUESTED** [review]

**Comment by dbaeumer** [comment]
Did not press the button.

**Review by dbaeumer — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
