### PR TITLE
Add proposed textDocument/inlayHints to protocol & client.

### PR DESCRIPTION
**Pull request by sam-mccall**
This addresses the FR https://github.com/microsoft/language-server-protocol/issues/956
And corresponds to the spec in https://github.com/microsoft/language-server-protocol/pull/1249

### CODE REVIEW

**Comment by sam-mccall** [comment]
@dbaeumer I'm guessing that as a new feature, this should all go under "proposed"?
Does this mean I should fold the spec text (i.e. https://github.com/microsoft/language-server-protocol/pull/1249) into this PR as a `protocol.inlayHints.proposed.md` file?

**Comment by dbaeumer** [comment]
@sam-mccall yes, this all has to go under proposed. And it is easier to keep the markdown spec part in sync if it is part of this repository as well. Adding it to the spec can be done when we think that the proposed API has reach some stability.

**Comment by sam-mccall** [comment]
@dbaeumer Gentle ping to get this back on your radar :-)

We've got a server implementation of this in clangd which is coming up to a release cycle, and are looking to add matching support in a client soon. Having the protocol landed in some form (proposed, or even just rough agreement on the protocol structure) would let us align on that. IME it's hard to rip out nonstandard extensions later especially if they're "richer" than the standard replacement.

**Comment by dbaeumer** [comment]
I was out on vacation. I will try to find out where VS Code is with that. What we can do is to add something that mirrors VS Code's proposed API. But then the proposed API might change if the VS Code API changes.

**Comment by dbaeumer** [comment]
VS Code will finalize the API this month. After that I think it is a good time to look into the PR again.

**Comment by rami3l** [comment]
@dbaeumer Gentle reminder: https://github.com/microsoft/vscode/issues/16221#issuecomment-1033827087 is now closed.

**Comment by dbaeumer** [comment]
Anyone interested in preparing a new PR or updating this one? Based on reviews we did we changed the VS Code API to allow more features (like navigating on inlay hints) which resulted in changes in the API.

**Comment by sam-mccall** [comment]
I can take another pass at it but probably for a few weeks.

If someone else wants to jump on it before then, please do!

**Comment by dbaeumer** [comment]
A first draft version is available here: https://github.com/microsoft/vscode-languageserver-node/blob/582ea52183d8a7c56fa617974de5cce8a322f0f7/protocol/src/common/proposed.InlayHints.ts#L6

**Comment by fwcd** [comment]
@dbaeumer Thanks for the nice work, just a question:

https://github.com/microsoft/vscode-languageserver-node/blob/37cf23b995720b53a19553c60c15a6fb04536a59/protocol/src/common/proposed.inlayHint.ts#L254

In the proposed LSP API, the range parameter of `InlayHintParams` is called `viewPort` whereas both the [new VSCode API](https://github.com/microsoft/vscode/blob/778b74a2159983ba09568d069ef9c9ecd858f783/src/vscode-dts/vscode.d.ts#L4719) and [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer/blob/3f4a095d3e8166d710919e06e21fc4cbc056b0ee/editors/code/src/lsp_ext.ts#L105) call it `range`. Any reason for not picking `range` for LSP too?

**Comment by matklad** [comment]
Yeah, `viewPort` would also be inconsistent with LSP's semantic highlighhting: https://github.com/microsoft/vscode-languageserver-node/blob/37cf23b995720b53a19553c60c15a6fb04536a59/protocol/src/common/protocol.semanticTokens.ts#L230

**Comment by fwcd** [comment]
Another slight inconsistency is `textDocument/inlayHint` (singular) in the current LSP proposal vs. `textDocument/semanticTokens` (plural). A lot of other `textDocument` requests are singular too though, so perhaps naming the request in singular is more idiomatic?

**Comment by dbaeumer** [comment]
I called it `viewPort` since this is how we called it in the inline values. I chatted with @jrieken that we should also make it consistent in the VS Code API. 

In general all request are singular. The semantic token one slipped in and it was too late to correct it since it already moved out of proposed and I didn't want to break it.

**Comment by dbaeumer** [comment]
If we choose range we could make it consistent since inline values is still proposed.

**Comment by dbaeumer** [comment]
OK. We will use range since a client can ask for a range that is not the viewPort.

**Comment by dbaeumer** [comment]
I will close the PR. The feature has shipped in 3.17

**Pull request closed without merging**
