### PR TITLE
Handle snippet edits in protocol conversion

### LINKED ISSUE #1414: Fix ProtocolConverter#asWorkspaceEdit to correctly support workspace edits with snippets
VS Code version 1.86 support new API to correctly implement the Snippet suppport. Here is what needs to be done:

- update grade to VS Code version 1.86 by adjusting the `client\package.json`. Things that need to be update are the `engine` property and the corresponding `devDependencies/@types/vscode`
- in the client folder run `npm run updateVSCodeVersion`

Change the code in the protocol converter here as follows: https://github.com/microsoft/vscode-languageserver-node/blob/2d33852e06ff9f180abd528be464f02b9bbd3079/client/src/common/protocolConverter.ts#L1088

- instead of calling the `replace` on the result, construct VS Code text edits yourself, correctly converting LSP `SnippetTextEdit` into VS Code `SnippetTextEdit`.
- if the edit as an annotation convert it as well
- mained the converted edits in  an array [TextEdit | SnippetTextEdit, WorkspaceEditEntryMetadata | undefined][]

When all edits are converted call `result.set` with this signature: https://github.com/microsoft/vscode/blob/56ed836ea9bae1602cf83bc286c7480b1370a99f/src/vscode-dts/vscode.d.ts#L3975

### PR DESCRIPTION
**Pull request by MariaSolOs**
Closes #1414

### CODE REVIEW

**Comment by dbaeumer** [comment]
Looks good to me expect one minor thing: we should re-enable the capability here: https://github.com/microsoft/vscode-languageserver-node/blob/2d33852e06ff9f180abd528be464f02b9bbd3079/client/src/common/client.ts#L1840

**Review by dbaeumer — CHANGES_REQUESTED** [review]
See last comment.

**Comment by MariaSolOs** [comment]
> See last comment.

Done! I'm really confused about the failing CI though...

**Comment by dbaeumer** [comment]
For some reason installing the dependencies failed. See https://dev.azure.com/ms/vscode-languageserver-node/_build/results?buildId=540252&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=0f0b056b-e9f7-5ce7-8817-a8ca2fd77699

**Comment by dbaeumer** [comment]
@MariaSolOs I was not able to make the build green. No idea why the failure happens. I merge in the changes by hand and created https://github.com/microsoft/vscode-languageserver-node/pull/1424

**Pull request closed without merging**
