### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dbaeumer**

### CODE REVIEW

**Comment by dbaeumer** [comment]
Update dependencies to fix depbot allert.

**Review by alexr00 — APPROVED** [review]

**Comment by Ehesp** [comment]
@dbaeumer @alexr00 would it be possible to publish a new release with this change?

**Comment by dbaeumer** [comment]
@Ehesp could you explain why?

**Comment by Ehesp** [comment]
@dbaeumer Sure, https://github.com/TypeFox/monaco-languageclient/blob/main/packages/client/package.json#L58 currently points to 8.0.2, which includes the v3 minimatch package, which causes this issue https://github.com/microsoft/vscode-languageserver-node/issues/1038

**Comment by dbaeumer** [comment]
Will look into it after end game week (which is this week).

**Pull request merged**
