### PR TITLE
Typeguards

### PR DESCRIPTION
**Pull request by felixfbecker**
- Adds tests for some typeguards.
- While writing tests, I noticed bugs - `Position.is()` and `Range.is()` would return `true` for `null` (but not for `undefined`). That made `Position.is` and `Range.is` ineffective as validating for a valid Position or Range, as there are no guarantees that the properties of a Position/Range can actually be accessed (and the LSP spec only allows `null` in specific places). As an example of why this is surprising, `Array.isArray()` returns `false` for `null`.
- Add typeguard and tests for `Hover` and contained types. I found myself needing these in multiple projects and given most interfaces have typeguards I thought it would be good to add them to the official package.
- package-lock.json changes came automatically from running `npm install`, seems like they weren't up to date with their package.json.

### CODE REVIEW

**Comment by dbaeumer** [comment]
Thanks. Valuable PR. Merged in the changes by hand. Mainly because:

- no semicolon at the end of a statement
- no reuse of what is available in `Is`
- add `Is.objectLiteral` to make the code consistent again

**Comment by felixfbecker** [comment]
> no semicolon at the end of a statement

It would be nice if this repo had tslint and/or prettier to avoid this. Would you be open to add this?

**Comment by dbaeumer** [comment]
Yes, I thought the same and I am open for a PR that adds this.

**Comment by felixfbecker** [comment]
Would you mind doing a release that includes this PR?

**Comment by dbaeumer** [comment]
Published Types 3.8.2

**Pull request closed without merging**
