### PR TITLE
Publish 8.0.2-next.3

### PR DESCRIPTION
**Pull request by dbaeumer**

### CODE REVIEW

**Review by aeschli — APPROVED** [review]

**Comment by DanTup** [comment]
@dbaeumer I'm not sure why, but some of the changes from #945 seem to be missing here (but others are included). If I regen the model from current code, I get the updated docs:

Screenshot 2022-06-01 at 14 56 48

I can send a PR with the updated version, although I don't know if it's deliberate (or there's something different between our setups that is causing a difference?).

**Comment by dbaeumer** [comment]
I will have a look.

**Comment by DanTup** [comment]
Thanks! The PR I intended to post this one was https://github.com/microsoft/vscode-languageserver-node/pull/971, that seems to be the one that regenerated it with some (but not all) of thesse changes.

**Comment by dbaeumer** [comment]
A new version should be available on the web.

**Pull request merged**
