### PR TITLE
Remove did change workspace folders dynamic registration

### PR DESCRIPTION
**Pull request by bmewburn**
#713

### CODE REVIEW

**Comment by dbaeumer** [comment]
@bmewburn removing this defeats the whole purpose of the listener. If a server doesn't want to be notified about workspace folder events since the client don't support them it should not call the method. The listener / event code is helper code to make the registration easier. I am closing the PR because without registering we should remove the whole code.

**Comment by dbaeumer** [comment]
Actually thinking about it again we should guard this against the server capability to support the auto registration.

**Comment by dbaeumer** [comment]
See comment https://github.com/microsoft/vscode-languageserver-node/issues/713#issuecomment-754510832. This requires a different change so. So I will close the PR since not registering at all makes the code wrong in other cases.

**Comment by bmewburn** [comment]
No problem, thanks for reviewing @dbaeumer

**Pull request closed without merging**
