### PR TITLE
add messageDetails to Diagnostic

### PR DESCRIPTION
**Pull request by RobbyCBennett**
PR on LSP repo: https://github.com/microsoft/language-server-protocol/pull/1825

Issue on LSP repo: https://github.com/microsoft/language-server-protocol/issues/1461

### CODE REVIEW

**Comment by RobbyCBennett** [comment]
This is expected to fail until the types are updated. See https://github.com/microsoft/language-server-protocol/pull/1825#issuecomment-1765209242

**Comment by dbaeumer** [comment]
I will close the PR for now. Please ping if you decide to continue working on this.

**Comment by RobbyCBennett** [comment]
I have already prepared this pull request as far as I am able to. The types are incorrect, and there doesn't appear to be any documentation for what repos the types come from.

This PR is waiting for other PRs first.

Please review the other PRs in https://github.com/microsoft/language-server-protocol/pull/1825#issuecomment-1765209242, which I think should mostly fix the types.

**Comment by dbaeumer** [comment]
Actually there seems to be a misunderstanding. The language server protocol is the specification. They don't define types. IMO your problem is that VS Code itself doesn't support `messageDetails` (https://github.com/microsoft/vscode/blob/6d1f607c6db3c6d9c842f77a12375ce9900ed53c/src/vscode-dts/vscode.d.ts#L6719) and this repository is the LSP implementation for VS Code. So to get this working `messageDetails` need to be implemented in VS Code first (see https://github.com/microsoft/vscode/pull/195727)

For the specification: we only merge something into the specification if there is at least one implementation for a client.

Please ping when the VS Code implementation is ready to be consumed and I will reopen the PR.

**Pull request closed without merging**
